server:
  port: 8087

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/final_project
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          api-client-oidc:
            provider: spring
            client-id: api-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8087/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: api-client-oidc
          api-client-authorization-code:
            provider: spring
            client-id: api-client
            client-secret: secret
            authorization-grant-type: authorization_code
            scope: api.read
            redirect-uri: "http://127.0.0.1:8087/authorized"
            client-name: api-client-authorization-code
        provider:
          soring:
            issuer-uri: http://auth-server:8087
